Remove | None syntax, as some clients may not be on python 3.1+
Summary:
Pre-commit is currently running python versions < 3.10, which don't include some of the latest python syntax. So it's failing with this error:

error: X | Y syntax for unions requires Python 3.10.

Pre-commit is defined here: https://github.com/facebookresearch/HolisticTraceAnalysis/blob/main/.github/workflows/pre-commit.yml

We can probably opt the pre-commit to later python versions, although it's unclear if any clients are still running older python. For now, we'll just use older syntax in our code.

Differential Revision: D79203577