Add fallback for missing event_args_1.0.0.yaml to prevent runtime error
Summary:
This diff adds a fallback mechanism in case the file
hta/configs/event_args_formats/event_args_1.0.0.yaml is not correctly included in the BUCK or TARGET's resources definition.

Without this, attempting to access the file may raise the following error at runtime:

```
  File "ads_training/p9e/open_hta/hta/common/trace_parser.py", line 26, in <module>
  File "hta/configs/parser_config.py", line 39, in <module>
  File "hta/configs/event_args_yaml_parser.py", line 87, in parse_event_args_yaml
NotADirectoryError: [Errno 20] Not a directory: '/proc/self/fd/6/hta/configs/event_args_formats/event_args_1.0.0.yaml'
```

Differential Revision: D73468457