Upgrade to python 3.12 in pre-commit test. (#275)
Summary:

Pre-commit is currently running python version 3.0, which doesn't include some of the latest python syntax.

Currently failing with: 

```
hta/common/call_stack.py:504: error: X | Y syntax for unions requires Python
3.10  [syntax]
            remapped_tids: Dict[int, Dict[int, int]] | None = None,
```

The comment previously suggested to keep the python versions consistent with .circleci/config.yml. But this file was deleted in https://github.com/facebookresearch/HolisticTraceAnalysis/pull/211 and replaced with .github/workflows/ci.yml, which uses version 3.10 and 3.12.

Differential Revision: D78677575